# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pyForceSense.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PyForceSenseWidget(object):
    def setupUi(self, PyForceSenseWidget):
        PyForceSenseWidget.setObjectName("PyForceSenseWidget")
        PyForceSenseWidget.resize(629, 615)
        self.curForceLabel = QtWidgets.QLabel(PyForceSenseWidget)
        self.curForceLabel.setGeometry(QtCore.QRect(27, 140, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.curForceLabel.setFont(font)
        self.curForceLabel.setStyleSheet("background-color: rgb(46, 255, 53)")
        self.curForceLabel.setFrameShape(QtWidgets.QFrame.Panel)
        self.curForceLabel.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.curForceLabel.setLineWidth(3)
        self.curForceLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.curForceLabel.setObjectName("curForceLabel")
        self.maxForceLabel = QtWidgets.QLabel(PyForceSenseWidget)
        self.maxForceLabel.setGeometry(QtCore.QRect(147, 140, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.maxForceLabel.setFont(font)
        self.maxForceLabel.setStyleSheet("background-color: rgb(255, 78, 81)")
        self.maxForceLabel.setFrameShape(QtWidgets.QFrame.Panel)
        self.maxForceLabel.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.maxForceLabel.setLineWidth(3)
        self.maxForceLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.maxForceLabel.setObjectName("maxForceLabel")
        self.serialOutputText = QtWidgets.QPlainTextEdit(PyForceSenseWidget)
        self.serialOutputText.setGeometry(QtCore.QRect(350, 10, 271, 211))
        self.serialOutputText.setReadOnly(True)
        self.serialOutputText.setObjectName("serialOutputText")
        self.forcePlot = PlotWidget(PyForceSenseWidget)
        self.forcePlot.setGeometry(QtCore.QRect(20, 260, 601, 221))
        self.forcePlot.setObjectName("forcePlot")
        self.resetMaxBtn = QtWidgets.QPushButton(PyForceSenseWidget)
        self.resetMaxBtn.setGeometry(QtCore.QRect(250, 140, 81, 21))
        self.resetMaxBtn.setObjectName("resetMaxBtn")
        self.comportCombo = QtWidgets.QComboBox(PyForceSenseWidget)
        self.comportCombo.setGeometry(QtCore.QRect(20, 10, 211, 28))
        self.comportCombo.setObjectName("comportCombo")
        self.connectButton = QtWidgets.QPushButton(PyForceSenseWidget)
        self.connectButton.setGeometry(QtCore.QRect(240, 10, 91, 29))
        self.connectButton.setObjectName("connectButton")
        self.logButton = QtWidgets.QPushButton(PyForceSenseWidget)
        self.logButton.setGeometry(QtCore.QRect(20, 90, 311, 31))
        self.logButton.setObjectName("logButton")
        self.logName = QtWidgets.QLineEdit(PyForceSenseWidget)
        self.logName.setGeometry(QtCore.QRect(20, 60, 211, 27))
        self.logName.setObjectName("logName")
        self.autoNameButton = QtWidgets.QPushButton(PyForceSenseWidget)
        self.autoNameButton.setGeometry(QtCore.QRect(240, 60, 91, 29))
        self.autoNameButton.setObjectName("autoNameButton")
        self.resetTareButton = QtWidgets.QPushButton(PyForceSenseWidget)
        self.resetTareButton.setGeometry(QtCore.QRect(250, 160, 81, 21))
        self.resetTareButton.setObjectName("resetTareButton")
        self.clearButton = QtWidgets.QPushButton(PyForceSenseWidget)
        self.clearButton.setGeometry(QtCore.QRect(350, 210, 271, 31))
        self.clearButton.setObjectName("clearButton")
        self.ForceDeviceInfo_Button = QtWidgets.QPushButton(PyForceSenseWidget)
        self.ForceDeviceInfo_Button.setGeometry(QtCore.QRect(20, 210, 311, 34))
        self.ForceDeviceInfo_Button.setObjectName("ForceDeviceInfo_Button")
        self.UpdateForceDeviceNr_Button = QtWidgets.QPushButton(PyForceSenseWidget)
        self.UpdateForceDeviceNr_Button.setGeometry(QtCore.QRect(100, 510, 261, 34))
        self.UpdateForceDeviceNr_Button.setObjectName("UpdateForceDeviceNr_Button")
        self.ForceDeviceNrInput_QSpinBox = QtWidgets.QSpinBox(PyForceSenseWidget)
        self.ForceDeviceNrInput_QSpinBox.setGeometry(QtCore.QRect(30, 510, 57, 35))
        self.ForceDeviceNrInput_QSpinBox.setObjectName("ForceDeviceNrInput_QSpinBox")
        self.ScaleFaktorInput_QLineEdit = QtWidgets.QLineEdit(PyForceSenseWidget)
        self.ScaleFaktorInput_QLineEdit.setGeometry(QtCore.QRect(160, 560, 131, 32))
        self.ScaleFaktorInput_QLineEdit.setObjectName("ScaleFaktorInput_QLineEdit")
        self.ScaleFaktorDisplay_Label = QtWidgets.QLabel(PyForceSenseWidget)
        self.ScaleFaktorDisplay_Label.setGeometry(QtCore.QRect(30, 560, 111, 24))
        self.ScaleFaktorDisplay_Label.setObjectName("ScaleFaktorDisplay_Label")
        self.UpdateScaleFaktor_Button = QtWidgets.QPushButton(PyForceSenseWidget)
        self.UpdateScaleFaktor_Button.setGeometry(QtCore.QRect(300, 560, 281, 31))
        self.UpdateScaleFaktor_Button.setObjectName("UpdateScaleFaktor_Button")
        self.line = QtWidgets.QFrame(PyForceSenseWidget)
        self.line.setGeometry(QtCore.QRect(10, 490, 611, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")

        self.retranslateUi(PyForceSenseWidget)
        QtCore.QMetaObject.connectSlotsByName(PyForceSenseWidget)

    def retranslateUi(self, PyForceSenseWidget):
        _translate = QtCore.QCoreApplication.translate
        PyForceSenseWidget.setWindowTitle(_translate("PyForceSenseWidget", "Form"))
        self.curForceLabel.setText(_translate("PyForceSenseWidget", "0"))
        self.maxForceLabel.setText(_translate("PyForceSenseWidget", "0"))
        self.resetMaxBtn.setText(_translate("PyForceSenseWidget", "Reset Max"))
        self.connectButton.setText(_translate("PyForceSenseWidget", "Connect"))
        self.logButton.setText(_translate("PyForceSenseWidget", "Start logging"))
        self.logName.setText(_translate("PyForceSenseWidget", "LogFile.txt"))
        self.autoNameButton.setText(_translate("PyForceSenseWidget", "Auto Name"))
        self.resetTareButton.setText(_translate("PyForceSenseWidget", "Reset Tare"))
        self.clearButton.setText(_translate("PyForceSenseWidget", "Clear"))
        self.ForceDeviceInfo_Button.setText(_translate("PyForceSenseWidget", "Force Device Info"))
        self.UpdateForceDeviceNr_Button.setText(_translate("PyForceSenseWidget", "Update Force Device Number"))
        self.ScaleFaktorDisplay_Label.setText(_translate("PyForceSenseWidget", "Scale Factor:"))
        self.UpdateScaleFaktor_Button.setText(_translate("PyForceSenseWidget", "Update Scale Faktor for Device"))
from pyqtgraph import PlotWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PyForceSenseWidget = QtWidgets.QWidget()
    ui = Ui_PyForceSenseWidget()
    ui.setupUi(PyForceSenseWidget)
    PyForceSenseWidget.show()
    sys.exit(app.exec_())
