# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pyDigitimer.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PyDigitimerWidget(object):
    def setupUi(self, PyDigitimerWidget):
        PyDigitimerWidget.setObjectName("PyDigitimerWidget")
        PyDigitimerWidget.resize(445, 257)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(PyDigitimerWidget.sizePolicy().hasHeightForWidth())
        PyDigitimerWidget.setSizePolicy(sizePolicy)
        PyDigitimerWidget.setStyleSheet("QSpinBox:disabled {\n"
"    background-color: #F0F0F0;\n"
"    color: #999999;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    color: #999999;\n"
"}")
        self.comportCombo = QtWidgets.QComboBox(PyDigitimerWidget)
        self.comportCombo.setGeometry(QtCore.QRect(20, 10, 211, 28))
        self.comportCombo.setObjectName("comportCombo")
        self.connectButton = QtWidgets.QPushButton(PyDigitimerWidget)
        self.connectButton.setGeometry(QtCore.QRect(240, 10, 91, 29))
        self.connectButton.setObjectName("connectButton")
        self.settingsBox = QtWidgets.QGroupBox(PyDigitimerWidget)
        self.settingsBox.setEnabled(False)
        self.settingsBox.setGeometry(QtCore.QRect(30, 60, 371, 161))
        self.settingsBox.setObjectName("settingsBox")
        self.freqSpin = QtWidgets.QSpinBox(self.settingsBox)
        self.freqSpin.setGeometry(QtCore.QRect(100, 30, 86, 33))
        self.freqSpin.setMinimum(1)
        self.freqSpin.setMaximum(200)
        self.freqSpin.setObjectName("freqSpin")
        self.onSpin = QtWidgets.QSpinBox(self.settingsBox)
        self.onSpin.setGeometry(QtCore.QRect(100, 70, 86, 33))
        self.onSpin.setMinimum(100)
        self.onSpin.setMaximum(10000)
        self.onSpin.setSingleStep(100)
        self.onSpin.setObjectName("onSpin")
        self.offSpin = QtWidgets.QSpinBox(self.settingsBox)
        self.offSpin.setGeometry(QtCore.QRect(100, 110, 86, 33))
        self.offSpin.setMinimum(100)
        self.offSpin.setMaximum(10000)
        self.offSpin.setSingleStep(100)
        self.offSpin.setObjectName("offSpin")
        self.label = QtWidgets.QLabel(self.settingsBox)
        self.label.setGeometry(QtCore.QRect(20, 40, 81, 19))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.settingsBox)
        self.label_2.setGeometry(QtCore.QRect(190, 40, 81, 19))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.settingsBox)
        self.label_3.setGeometry(QtCore.QRect(20, 80, 81, 19))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.settingsBox)
        self.label_4.setGeometry(QtCore.QRect(20, 120, 81, 19))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.settingsBox)
        self.label_5.setGeometry(QtCore.QRect(190, 80, 81, 19))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.settingsBox)
        self.label_6.setGeometry(QtCore.QRect(190, 120, 81, 19))
        self.label_6.setObjectName("label_6")
        self.setButton = QtWidgets.QPushButton(self.settingsBox)
        self.setButton.setGeometry(QtCore.QRect(260, 110, 89, 35))
        self.setButton.setObjectName("setButton")

        self.retranslateUi(PyDigitimerWidget)
        QtCore.QMetaObject.connectSlotsByName(PyDigitimerWidget)

    def retranslateUi(self, PyDigitimerWidget):
        _translate = QtCore.QCoreApplication.translate
        PyDigitimerWidget.setWindowTitle(_translate("PyDigitimerWidget", "Digitimer pulse generator"))
        self.connectButton.setText(_translate("PyDigitimerWidget", "Connect"))
        self.settingsBox.setTitle(_translate("PyDigitimerWidget", "Settings"))
        self.label.setText(_translate("PyDigitimerWidget", "Frequency:"))
        self.label_2.setText(_translate("PyDigitimerWidget", "Hz"))
        self.label_3.setText(_translate("PyDigitimerWidget", "OnTime:"))
        self.label_4.setText(_translate("PyDigitimerWidget", "OffTime:"))
        self.label_5.setText(_translate("PyDigitimerWidget", "ms"))
        self.label_6.setText(_translate("PyDigitimerWidget", "ms"))
        self.setButton.setText(_translate("PyDigitimerWidget", "Set"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PyDigitimerWidget = QtWidgets.QWidget()
    ui = Ui_PyDigitimerWidget()
    ui.setupUi(PyDigitimerWidget)
    PyDigitimerWidget.show()
    sys.exit(app.exec_())
